import { LegalLayout } from '../components/LegalLayout'

export function Legal() {
  return (
    <LegalLayout title="Legal Disclaimer" version="0.1 (draft)" effectiveDate="[Insert date of publication]">
      <section>
        <h2>1. What this page is</h2>
        <p>
          This Legal Disclaimer, together with our <a href="/terms">Terms &amp; Conditions</a> and{' '}
          <a href="/privacy">Privacy Policy</a>, sets out the basis on which Connexus (<strong>[Insert registered
          business name], ABN [Insert ABN]</strong>) makes its platform available to you. If anything here conflicts
          with the Terms &amp; Conditions, the Terms &amp; Conditions govern.
        </p>
      </section>

      <section>
        <h2>2. Connexus is not legal, WHS, or clinical advice</h2>
        <p>
          Connexus is a software tool for organising and documenting a psychosocial risk assessment. It is not a
          substitute for a qualified work health and safety consultant, an employment lawyer, or a registered
          psychologist. Nothing generated by the platform, including hazard descriptions, control suggestions from
          the built-in reference library, legislation citations, or exported reports, constitutes legal, WHS, HR, or
          clinical advice, and using Connexus does not create an advisory or professional relationship between you
          and Connexus.
        </p>
        <p>
          You should seek independent professional advice before making decisions that affect your workers' health,
          safety, or employment based on anything produced through the platform.
        </p>
      </section>

      <section>
        <h2>3. What the platform does and doesn't do</h2>
        <p>Connexus gives you structured tools to:</p>
        <ul>
          <li>Record hazards against a reference library aligned to the model WHS psychosocial regulations and each state or territory's code of practice</li>
          <li>Track actions, owners, and due dates arising from those hazards</li>
          <li>Log worker consultation records</li>
          <li>Export a PDF report, and cryptographically fingerprint an assessment once you close it</li>
        </ul>
        <p>
          Connexus does not review, audit, verify, or certify the accuracy of anything you or your team enter. The
          quality of an assessment depends entirely on the information put into it. Using the platform, including
          closing and sealing an assessment, does not by itself demonstrate or guarantee compliance with the Work
          Health and Safety Act, the psychosocial hazard regulations, or any code of practice in your state or
          territory, those obligations rest on you as the person conducting a business or undertaking (PCBU), not on
          the software.
        </p>
      </section>

      <section>
        <h2>4. Currency of legislation content</h2>
        <p>
          We take reasonable care to keep the legislation and code-of-practice citations in the hazard library
          current, but WHS legislation changes over time and differs by state and territory. We don't guarantee that
          any citation reflects the current legal position at the moment you rely on it. Verify current requirements
          directly with your state or territory's WHS regulator, or with a qualified adviser, before relying on a
          citation.
        </p>
      </section>

      <section>
        <h2>5. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, Connexus is not liable for any indirect or consequential loss
          arising from your use of the platform, or for the outcome of any WHS inquiry, regulatory action, or dispute
          connected to an assessment you conducted using it. Nothing in this page excludes, restricts, or modifies
          any guarantee, right, or remedy you have under the Australian Consumer Law that cannot lawfully be
          excluded. See our <a href="/terms">Terms &amp; Conditions</a> for the full limitation of liability clause.
        </p>
      </section>

      <section>
        <h2>6. Intellectual property</h2>
        <p>
          The Connexus platform, including its design, hazard library, control-hierarchy framework, report layout,
          and underlying code, belongs to us or our licensors and is protected by the Copyright Act 1968 (Cth). The
          assessment data you enter, your hazards, actions, and consultation records, remains yours; we don't claim
          ownership of it. See Section 5 (License &amp; usage) of our <a href="/terms">Terms &amp; Conditions</a> for
          what you can and can't do with the platform itself.
        </p>
      </section>

      <section>
        <h2>7. Third-party services</h2>
        <p>
          Connexus relies on third-party infrastructure to operate: <strong>Stripe</strong> for payment processing
          and <strong>Render</strong> for application hosting. We're not responsible for the availability, content,
          or practices of these or any other third-party service, including any external site you reach via a link
          from Connexus. Their own terms and privacy policies apply to your use of them. See our{' '}
          <a href="/privacy">Privacy Policy</a> for where these providers are located and what they can access.
        </p>
      </section>

      <section>
        <h2>8. Governing law</h2>
        <p>
          This page is governed by the laws of [Insert state/territory], Australia. See Section 10 of our{' '}
          <a href="/terms">Terms &amp; Conditions</a> for the full governing law and dispute resolution clause.
        </p>
      </section>

      <section>
        <h2>9. Contact</h2>
        <p>
          Questions about this page: <strong>[Insert support email]</strong>.
        </p>
      </section>
    </LegalLayout>
  )
}
